services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Variáveis de ambiente
      - DB_SERVER=mysql-db            
      - DB_USER=${dbUser}                  
      - DB_PASSWORD=${dbPwd}      
      - DB_NAME=${dbName}   
      - USE_DOCKER_DB=true
      - DB_PORT=${dbPort}           
      - ASPNETCORE_ENVIRONMENT=Development

    depends_on:
      - mysql-db 
    restart: always

  mysql-db: 
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${dbPwd}
      - MYSQL_DATABASE=${dbName}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
